### PR TITLE
[WRF] Ensure nested directories are handled properly in metastore writes

### PR DESCRIPTION
**Pull request by saskatchuwan**
Within a study for WRF, we may use subdirectories to further organize output files that come from different sim runs. Currently, if we have an output file in a nested subfolder, a new StudyArea within the metastore would be created named after that subfolder. Instead, we want to ensure that:
1. Root folder determines `StudyArea`
2. StudyAreaChunks are always written in metastore like `<study_area>/chunks/<chunk_name>` regardless of folder organization in source bucket destination

GCS structure
```
/NYC_Heat
    /Summer_2010
         met_em1.nc
    /Summer_2015
         met_em20.nc
   ....
```
should result in

Metastore structure:
```
NYC_Heat            (StudyArea)
    /chunks
        met_em1      (StudyAreaChunk)
        met_em20   (StudyAreaChunk)
        ...
```

### CODE REVIEW

**Comment by saskatchuwan** [comment]
@MadhaviJain90 @waltaskew Cna you review the structure of the metastore data? This will probably be the last thing we should fix in the features portion of the pipeline. This will allow wrf team to do their own file organization in GCS without it affecting the organization of the metastore entries

**Review by waltaskew — APPROVED** [review]
LGTM

**Comment by saskatchuwan** [comment]
> Looks great. Although we could have a nested directory naming convention as - Season_YYYY_xxp e.g. Summer_2010_99p. xx being the percentile. This shouldn't affect the code execution, right? I want to minimize having to look for separate docs to confirm which WRF run corresponds which percentile and year

Yeah that's fine the naming of the subfolders can be whatever you think will be the most informative - we won't use the names of the subfolders for the metastore. It's only the name of the root folder that needs to follow a specific naming convention. I've documented these details in the atmoML data pipeline doc in notion. So take a look and feel free to leave feedback.comments there!

**Review by MadhaviJain90 — COMMENTED** [review]
Looks good

**Pull request merged**
