### PR TITLE
Avoid division by zero in NSE calculation

### PR DESCRIPTION
**Pull request by tatianawu**

### CODE REVIEW

**Review by waltaskew — APPROVED** [review]
Would be great to add a test exercising this

**Comment by tatianawu** [comment]
> Would be great to add a test exercising this

Do you mean adding a test that checks the behavior when we do divide by zero? It doesn't fail, but the tensor will include NaN and inf values.

**Comment by waltaskew** [comment]
> > Would be great to add a test exercising this
> 
> Do you mean adding a test that checks the behavior when we do divide by zero? It doesn't fail, but the tensor will include NaN and inf values.

A mean a test which demonstrates us successfully evading a situation in which we would otherwise divide by zero and the result wouldn't include NaNs or infs

**Comment by tatianawu** [comment]
> > > Would be great to add a test exercising this
> > 
> > 
> > Do you mean adding a test that checks the behavior when we do divide by zero? It doesn't fail, but the tensor will include NaN and inf values.
> 
> I mean a test which demonstrates us successfully evading a situation in which we would otherwise divide by zero and the result wouldn't include NaNs or infs

Done.

**Pull request merged**
