### PR TITLE
Only Write Chunk Errors From Chunk Cloud Function

### PR DESCRIPTION
**Pull request by waltaskew**
- Only attempt to write feature chunk errors to the metastore from the feature chunk cloud function. Accomplish this by adding an argument to the `retry_and_report_errors` decorator for additional custom error handling and adding the additional metastore write when decorating the feature chunk cloud function.

### CODE REVIEW

**Review by rsutormin — APPROVED** [review]
I see that you're not testing this code, right? I guess it's something not very easy to do?

**Comment by waltaskew** [comment]
> I see that you're not testing this code, right? I guess it's something not very easy to do?

The change here is that `write_study_area_metadata` no longer calls `_write_chunk_metastore_error`. All the other error reporting stuff is staying the same, and I already have tests covering it. I didn't add a test ensuring that the `_write_chunk_metastore_error` call doesn't happen because it's a little awkward to assert that a thing doesn't happen, but I can do so if you think that's useful.

**Review by rsutormin — APPROVED** [review]
Well, when I see some complex logic that you change in prod code and then you don't have to also touch test code to compensate the change, my instincts tell me that there is poor test coverage. :)
In most cases I vote for extracting some complex logic from top level main class/file to avoid exactly the situation when it's not super convenient to add tests.
In this particular case I rely on your understanding of what test coverage is enough. Just general thing that I felt I need to flag.

**Comment by waltaskew** [comment]
> Well, when I see some complex logic that you change in prod code and then you don't have to also touch test code to compensate the change, my instincts tell me that there is poor test coverage. :) In most cases I vote for extracting some complex logic from top level main class/file to avoid exactly the situation when it's not super convenient to add tests. In this particular case I rely on your understanding of what test coverage is enough. Just general thing that I felt I need to flag.

This PR keeps existing error reporting & retry logic the same. The tests are helpfully ensuring that the behavior stays the same. The tests are in here:
https://github.com/UrbanSystemsLab/climateiq-cnn/blob/70c827e3947ea61904df2913a435c021bc20e661/usl_pipeline/cloud_functions/main_test.py#L127
https://github.com/UrbanSystemsLab/climateiq-cnn/blob/70c827e3947ea61904df2913a435c021bc20e661/usl_pipeline/cloud_functions/main_test.py#L186

The only change is that `_write_chunk_metastore_error` is only called when `build_feature_matrix` errors, not when `write_study_area_metadata` errors. So the test I could add is a test ensuring that `write_study_area_metadata` does not attempt to call `write_study_area_metadata` when it errors.

**Pull request merged**
